// Generates functions/_routes.js from the built `dist` output.
// Runs automatically after `astro build` (see package.json "build" script).
//
// The generated file is a Set of every real static route (directory routes end
// with '/'). functions/_middleware.js uses it as an allowlist: genuine pages are
// always served, and only legacy/non-existent paths are candidates for redirect.
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const root = process.cwd();
const distDir = join(root, 'dist');
const outFile = join(root, 'functions', '_routes.js');

const routes = new Set();

function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      walk(full);
      continue;
    }
    if (!entry.endsWith('.html')) continue;
    const rel = relative(distDir, full).split(sep).join('/');
    if (rel === '404.html') continue; // error page is not a navigable route
    if (rel.endsWith('/index.html')) {
      const base = rel.slice(0, -'index.html'.length);
      routes.add(base === '' ? '/' : '/' + base); // directory route, keeps trailing slash
    } else {
      routes.add('/' + rel); // top-level/standalone .html, e.g. /some-page.html
    }
  }
}

walk(distDir);

const sorted = [...routes].sort();
const body =
  '// AUTO-GENERATED by tools/generate-routes.mjs from dist after build. Do not edit.\n' +
  '// Real static routes; directory routes end with "/".\n' +
  'export const ROUTES = new Set(' + JSON.stringify(sorted) + ');\n';

writeFileSync(outFile, body);
console.log(`generate-routes: ${sorted.length} routes -> ${relative(root, outFile)}`);
